apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Chart.Name }}
  labels:
    app: {{ .Chart.Name }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Chart.Name }}
  template:
    metadata:
      labels:
        app: {{ .Chart.Name }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          resources:
            limits:
              cpu: {{ .Values.resources.limits.cpu }}
              memory: {{ .Values.resources.limits.memory }}
            requests:
              cpu: {{ .Values.resources.requests.cpu }}
              memory: {{ .Values.resources.requests.memory }}
          env:
            - name: DATABASE_HOSTNAME
              valueFrom:
                secretKeyRef:
                  name: meteored-env
                  key: DATABASE_HOSTNAME
            - name: DATABASE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: meteored-env
                  key: DATABASE_USERNAME
            - name: DATABASE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: meteored-env
                  key: DATABASE_PASSWORD
            - name: GROQ_API_KEY
              valueFrom:
                secretKeyRef:
                  name: meteored-env
                  key: GROQ_API_KEY
