-- Migration table sequence creation 
CREATE SEQUENCE WEATHER.SEQMET
START WITH 1
INCREMENT BY 1
NOCACHE
NOCYCLE;

-- Table creation 
CREATE TABLE WEATHER.METEORED (
    "ID"      NUMBER(19) DEFAULT WEATHER.SEQMET.NEXTVAL,
    "DATE"    VARCHAR2(10) NOT NULL UNIQUE,
    "NAME"    VARCHAR2(10),
    "ICON"    VARCHAR2(80),
    "DESC"    VARCHAR2(20),
    "TEMP"    VARCHAR2(4),
    "SENS"    VARCHAR2(4),
    "TMAX"    VARCHAR2(4),
    "TMIN"    VARCHAR2(7),
    "WIND"    VARCHAR2(15),
    "RAIN"    VARCHAR2(20),
    "PROV"    VARCHAR2(20),
    "CIDADE"  NUMBER(19),
    "PUBLISH" TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Table index and contraint creation 
CREATE UNIQUE INDEX WEATHER."METEORED_IDX" ON WEATHER."METEORED" ("ID");
ALTER TABLE WEATHER.METEORED ADD CONSTRAINT METEORED_FK FOREIGN KEY ("CIDADE") REFERENCES ADMIN.CIDADE("ID");
ALTER TABLE WEATHER.METEORED ADD CONSTRAINT METEORED_PK PRIMARY KEY("ID") USING INDEX WEATHER."METEORED_IDX" ENABLE;

-- Add comments to the table 
COMMENT ON TABLE  WEATHER.METEORED IS 'Tabela de meteorologia';
COMMENT ON COLUMN WEATHER.METEORED."ID" IS 'Chave primaria';
COMMENT ON COLUMN WEATHER.METEORED."DATE" IS 'Previsão para data';
COMMENT ON COLUMN WEATHER.METEORED."NAME" IS 'Dia da semana';
COMMENT ON COLUMN WEATHER.METEORED."ICON" IS 'Icon da previsão';
COMMENT ON COLUMN WEATHER.METEORED."DESC" IS 'Descrição da previsão';
COMMENT ON COLUMN WEATHER.METEORED."TEMP" IS 'Temperatura atual';
COMMENT ON COLUMN WEATHER.METEORED."SENS" IS 'Sensação termica';
COMMENT ON COLUMN WEATHER.METEORED."TMAX" IS 'Tamperatura macxíma';
COMMENT ON COLUMN WEATHER.METEORED."TMIN" IS 'Temperatura miníma';
COMMENT ON COLUMN WEATHER.METEORED."WIND" IS 'Rajadas de vento';
COMMENT ON COLUMN WEATHER.METEORED."RAIN" IS 'Quantidade de chuva';
COMMENT ON COLUMN WEATHER.METEORED."PROV" IS 'Provabilidade de chuva';
COMMENT ON COLUMN WEATHER.METEORED."CIDADE" IS 'Cidade da previsão';
COMMENT ON COLUMN WEATHER.METEORED.PUBLISH IS 'Data da publicação';