-- Migration table sequence creation 
CREATE SEQUENCE WEATHER.SEQHOR
START WITH 1
INCREMENT BY 1
NOCACHE
NOCYCLE;

-- Table creation 
CREATE TABLE WEATHER.METHOUR (
    "ID"   NUMBER(19) DEFAULT WEATHER.SEQHOR.NEXTVAL,
    "HORA" VARCHAR2(5),  
    "TEMP" VARCHAR2(10),
    "SENS" VARCHAR2(10),
    "RAIN" VARCHAR2(10),
    "UMID" VARCHAR2(10),
    "DESC" VARCHAR2(100),
    "WIND" VARCHAR2(20),
    "BURS" VARCHAR2(20),
    "PRES" VARCHAR2(20),
    "IFPS" VARCHAR2(20), 
    "ICON" VARCHAR2(255),
    "CIDADE"  NUMBER(19),
    "PUBLISH" TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Table index and contraint creation 
CREATE UNIQUE INDEX WEATHER."METHOUR_IDX" ON WEATHER."METHOUR" ("ID");
ALTER TABLE WEATHER.METHOUR ADD CONSTRAINT METHOUR_FK FOREIGN KEY ("CIDADE") REFERENCES ADMIN.CIDADE("ID");
ALTER TABLE WEATHER.METHOUR ADD CONSTRAINT METHOUR_PK PRIMARY KEY("ID") USING INDEX WEATHER."METHOUR_IDX" ENABLE;

-- Add comments to the table 
COMMENT ON TABLE  WEATHER.METHOUR IS 'Tabela de meteorologia por hora';
COMMENT ON COLUMN WEATHER.METHOUR."ID" IS 'Chave primaria';
COMMENT ON COLUMN WEATHER.METHOUR."HORA" IS 'Hora da meteorologia';
COMMENT ON COLUMN WEATHER.METHOUR."TEMP" IS 'Temperatura da meteorologia';
COMMENT ON COLUMN WEATHER.METHOUR."SENS" IS 'Sensação da meteorologia';
COMMENT ON COLUMN WEATHER.METHOUR."RAIN" IS 'Chuva da meteorologia';
COMMENT ON COLUMN WEATHER.METHOUR."UMID" IS 'Umidade da meteorologia';
COMMENT ON COLUMN WEATHER.METHOUR."DESC" IS 'Descrição da meteorologia';
COMMENT ON COLUMN WEATHER.METHOUR."WIND" IS 'Vento da meteorologia';
COMMENT ON COLUMN WEATHER.METHOUR."BURS" IS 'Rajadas da meteorologia';
COMMENT ON COLUMN WEATHER.METHOUR."PRES" IS 'Pressão da meteorologia';
COMMENT ON COLUMN WEATHER.METHOUR."IFPS" IS 'Indice UV da meteorologia';
COMMENT ON COLUMN WEATHER.METHOUR."ICON" IS 'Icone da meteorologia';
COMMENT ON COLUMN WEATHER.METHOUR."CIDADE" IS 'Cidade da meteorologia';
COMMENT ON COLUMN WEATHER.METHOUR."PUBLISH" IS 'Data e hora da meteorologia';