-- Migration table sequence creation 
CREATE SEQUENCE METEORED_ID
START WITH 1
INCREMENT BY 1
NOCACHE
NOCYCLE;

-- Table creation 
CREATE TABLE METEORED (
    "ID"      NUMBER(19) DEFAULT METEORED_ID.NEXTVAL,
    "DATE"    VARCHAR2(10) NOT NULL UNIQUE,
    "NAME"    VARCHAR2(10),
    "ICON"    VARCHAR2(80),
    "DESC"    VARCHAR2(20),
    "TEMP"    VARCHAR2(4),
    "SENS"    VARCHAR2(4),
    "TMAX"    VARCHAR2(4),
    "TMIN"    VARCHAR2(7),
    "WIND"    VARCHAR2(15),
    "DFPS"    VARCHAR2(20),
    "RAIN"    VARCHAR2(20),
    "PROV"    VARCHAR2(20),
    "MOON"    VARCHAR2(20),
    "ICMO"    VARCHAR2(80),
    "CIDADE"  NUMBER(19),
    "PUBLISH" TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Table index and contraint creation 
CREATE UNIQUE INDEX "METEORED_IDX" ON "METEORED" ("ID");
ALTER TABLE METEORED ADD CONSTRAINT METEORED_FK FOREIGN KEY (CIDADE) REFERENCES CIDADE(ID);
ALTER TABLE METEORED ADD CONSTRAINT METEORED_PK PRIMARY KEY(ID) USING INDEX "METEORED_IDX" ENABLE;

-- Add comments to the table 
COMMENT ON TABLE  METEORED IS 'Tabela de meteorologia';
COMMENT ON COLUMN METEORED."ID" IS 'Chave primaria';
COMMENT ON COLUMN METEORED."DATE" IS 'Previsão para data';
COMMENT ON COLUMN METEORED."NAME" IS 'Dia da semana';
COMMENT ON COLUMN METEORED."ICON" IS 'Icon da previsão';
COMMENT ON COLUMN METEORED."DESC" IS 'Descrição da previsão';
COMMENT ON COLUMN METEORED."TEMP" IS 'Temperatura atual';
COMMENT ON COLUMN METEORED."SENS" IS 'Sensação termica';
COMMENT ON COLUMN METEORED."TMAX" IS 'Tamperatura macxíma';
COMMENT ON COLUMN METEORED."TMIN" IS 'Temperatura miníma';
COMMENT ON COLUMN METEORED."WIND" IS 'Rajadas de vento';
COMMENT ON COLUMN METEORED.DFPS IS 'Descrição de indice fps';
COMMENT ON COLUMN METEORED."RAIN" IS 'Quantidade de chuva';
COMMENT ON COLUMN METEORED."PROV" IS 'Provabilidade de chuva';
COMMENT ON COLUMN METEORED."MOON" IS 'faze atual da lua';
COMMENT ON COLUMN METEORED."ICMO" IS 'icone faze atual da lua';
COMMENT ON COLUMN METEORED."CIDADE" IS 'Cidade da previsão';
COMMENT ON COLUMN METEORED.PUBLISH IS 'Data da publicação';