-- Migration table sequence creation 
CREATE SEQUENCE WEATHER.SEQMOON
START WITH 1
INCREMENT BY 1
NOCACHE
NOCYCLE;

-- Table creation 
CREATE TABLE WEATHER.MOON (
    "ID"      NUMBER(19) DEFAULT WEATHER.SEQMOON.NEXTVAL,
    "DATE"    VARCHAR2(10) NOT NULL UNIQUE,
    "NAME"    VARCHAR2(20),
    "ICON"    VARCHAR2(80),
    "PUBLISH" TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Table index and contraint creation 
CREATE UNIQUE INDEX WEATHER."MOON_IDX" ON WEATHER."MOON" ("ID");
ALTER TABLE WEATHER.MOON ADD CONSTRAINT MOON_PK PRIMARY KEY(ID) USING INDEX WEATHER."MOON_IDX" ENABLE;

GRANT SELECT, INSERT, UPDATE, DELETE ON WEATHER.MOON TO ADMIN;

-- Add comments to the table 
COMMENT ON TABLE  WEATHER.MOON IS 'Tabela de meteorologia';
COMMENT ON COLUMN WEATHER.MOON."ID" IS 'Chave primaria';
COMMENT ON COLUMN WEATHER.MOON."DATE" IS 'Dia do mês';
COMMENT ON COLUMN WEATHER.MOON."NAME" IS 'Nome da lua';
COMMENT ON COLUMN WEATHER.MOON."ICON" IS 'Icon da lua';
COMMENT ON COLUMN WEATHER.MOON."PUBLISH" IS 'Data da publicação';