CREATE USER WEATHER IDENTIFIED BY "Inneo(2025)#"
  DEFAULT TABLESPACE data
  TEMPORARY TABLESPACE temp
  QUOTA UNLIMITED ON data;
  
GRANT CREATE SESSION TO WEATHER;        -- Permite login
GRANT CREATE TABLE TO WEATHER;          -- Criar tabelas
GRANT CREATE VIEW TO WEATHER;           -- Criar views
GRANT CREATE SEQUENCE TO WEATHER;       -- Criar sequences
GRANT CREATE PROCEDURE TO WEATHER;      -- Criar procedures 

GRANT SELECT, INSERT, UPDATE, DELETE ON WEATHER.METEORED TO ADMIN;
GRANT SELECT, INSERT, UPDATE, DELETE ON WEATHER.MOON TO ADMIN;
GRANT SELECT, REFERENCES ON ADMIN.CIDADE TO WEATHER;