image:
  repository: inneobr/cronus
  tag: latest

resources:
  limits:
    cpu: 500m
    memory: 256Mi

service:
  type: NodePort
  port: 80

env:
  DATABASE_HOSTNAME: ""
  DATABASE_USERNAME: ""
  DATABASE_PASSWORD: ""
  GROQ_API_KEY: ""